---
- hosts: 127.0.0.1
  vars:
    base_install_packages:
      - readline
      - gcc
      - wget
      - tmux
      - htop
      - zsh
      - neovim
      - sqlite
      - wget
      - gh
      - jq
      - yarn
      - gpg
      - gawk
      - thefuck
      - fzy
      - fzf
      - pyenv
      - readline
      - xz
      - openssl
      - sqlite3
      - zlib
      - asdf
      - ripgrep
      - terraform
      - waypoint
      - kubectl
      - awscli
    cask_install_packages:
      - bitwarden
      - docker
  connection: local
  tasks:
    - name: Install apps with homebrew
      homebrew: name={{ item }} state=present
      loop: "{{ base_install_packages }}"
    - name: Install cask packages
      homebrew_cask: name={{ item }} state=present
      loop: "{{ cask_install_packages }}"
